CREATE TABLE empleados (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR2(100) NOT NULL,
    apellido VARCHAR2(100) NOT NULL,
    edad NUMBER(3),
    salario NUMBER(10,2),
    fecha_ingreso DATE,
    activo CHAR(1) DEFAULT 'S',
    CONSTRAINT pk_empleados PRIMARY KEY (id)
);

INSERT INTO empleados (
    nombre,
    apellido,
    edad,
    salario,
    fecha_ingreso
)
VALUES (
    'Juan',
    'Perez',
    25,
    2500.50,
    SYSDATE
);

SELECT
    id,
    nombre,
    apellido,
    salario
FROM empleados
WHERE salario > 2000
ORDER BY salario DESC;

DELETE FROM empleados
WHERE edad > 65;

SELECT
    e.id,
    e.nombre,
    d.nombre_departamento
FROM empleados e
INNER JOIN departamentos d
    ON e.departamento_id = d.id;

SELECT
    departamento_id,
    COUNT(*) AS total_empleados,
    AVG(salario) AS salario_promedio
FROM empleados
GROUP BY departamento_id;

SELECT
    nombre,
    salario
FROM empleados
WHERE salario >
(
    SELECT AVG(salario)
    FROM empleados
);

CREATE OR REPLACE VIEW vw_empleados_activos AS
SELECT
    id,
    nombre,
    apellido,
    salario
FROM empleados
WHERE activo = 'S';

SELECT *
FROM empleados
WHERE activo = 'S'
    AND salario > 1000
    AND edad >= 18
    AND edad <= 65
    AND nombre IS NOT NULL
    AND apellido IS NOT NULL
    AND fecha_ingreso >= TO_DATE('01/01/2020','DD/MM/YYYY')
    AND salario > 1000
    AND edad >= 18
    AND edad <= 65
    AND nombre IS NOT NULL
    AND apellido IS NOT NULL
    AND fecha_ingreso >= TO_DATE('01/01/2020','DD/MM/YYYY')
    AND salario > 1000
    AND edad >= 18
    AND edad <= 65
    AND nombre IS NOT NULL
    AND apellido IS NOT NULL
    AND fecha_ingreso >= TO_DATE('01/01/2020','DD/MM/YYYY')
    AND salario > 1000
    AND edad >= 18
    AND edad <= 65
    AND nombre IS NOT NULL
    AND apellido IS NOT NULL
    AND fecha_ingreso >= TO_DATE('01/01/2020','DD/MM/YYYY')
    AND salario > 1000
    AND edad >= 18
    AND edad <= 65
    AND nombre IS NOT NULL
    AND apellido IS NOT NULL
    AND fecha_ingreso >= TO_DATE('01/01/2020','DD/MM/YYYY')
ORDER BY
    apellido,
    nombre,
    salario DESC;